plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java-library'
	id 'maven-publish'
}

group = 'dev.hyunlab'
version = '21.4.260303-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()	
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'com.github.ben-manes.caffeine:caffeine'	
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'	
	annotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Excel 처리 라이브러리
	implementation 'org.apache.poi:poi:5.5.1'
	implementation 'org.apache.poi:poi-ooxml:5.5.1'
	
	// Markdown 처리 라이브러리
	implementation 'org.commonmark:commonmark:0.24.0'

	
	// JWT 구현체 및 JSON 파서
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6' 


}

tasks.named('test') {
	useJUnitPlatform()
}

publishing {
	publications {
		maven(MavenPublication) {
			groupId = 'dev.hyunlab'
			artifactId = 'hyun-lib'
			version = '21.4.260303-SNAPSHOT'

			from components.java

			versionMapping {
				usage('java-api') {
					fromResolutionOf('runtimeClasspath')
				}
				usage('java-runtime') {
					fromResolutionResult()
				}
			}
		}
	}
}